apiVersion: v1
kind: Service
metadata:
  name: {{ include "recommendation-platform.fullname" . }}
  labels: {{- include "recommendation-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "recommendation-platform.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
